name: MkDocsTest

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: execute apt install
        run: |
          sudo apt update
          sudo apt install -y hub

      - name: setup python
        if: ${{ success() }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.0'

      - name: checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: pip install
        if: ${{ success() }}
        run: |
          pip install -r requirements.txt 

      - name: setup mkdocs project
        if: ${{ success() }}
        env:
          REF: ${{ github.ref }}
        run: |
          export VER=`echo "${REF##*/}"`
          echo "version=${VER}" >> $GITHUB_ENV
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --local user.name "${GITHUB_ACTOR}"
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git fetch

      - name: check mike list previous
        if: ${{ success() }}
        continue-on-error: true
        run: |
          mike list | grep ${{env.version}}
          if [ $? ]; then
            mike delete ${{env.version}}
          fi

      - name: build mkdocs
        run: |
          mike deploy ${{env.version}}

      - name: push and pull request
        if: ${{ success() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout gh-pages
          hub push origin gh-pages
          hub pull-request -b release-pages -m "Release MkDocs ver.${{ env.version }}"

